apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: mc-tritonserver-23.01-py3-4
  labels:
    name: mc-tritonserver-23.01-py3-4
  annotations:
    maxLoadingConcurrency: "2"
    openshift.io/display-name: Triton runtime 23.01 - added on 20230809
spec:
  supportedModelFormats:
    - name: keras
      version: "2"
      autoSelect: true
    - name: onnx
      version: "1"
      autoSelect: true
    - name: pytorch
      version: "1"
      autoSelect: true
    - name: tensorflow
      version: "1"
      autoSelect: true
    - name: python
      version: "1"
      autoSelect: true
    - name: tensorrt
      version: "7"
      autoSelect: true
    - name: bls
      version: "1"
      autoSelect: true
    - name: ensemble
      version: "1"
      autoSelect: true
    - name: fil
      version: "1"
      autoSelect: true
  protocolVersions:
    - grpc-v2
  multiModel: true
  grpcEndpoint: port:8085
  grpcDataEndpoint: port:8001
  containers:
    - name: triton
      image: <customer-artifactory-path>/tritonserver:23.01-py3
      command:
        - /bin/sh
      args:
        - -c
        - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models;
          exec tritonserver "--model-repository=/models/_triton_models"
          "--model-control-mode=explicit" "--strict-model-config=false"
          "--strict-readiness=false" "--allow-http=true"
          "--allow-sagemaker=false" '
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "5"
          memory: 1Gi
      livenessProbe:
        exec:
          command:
            - curl
            - --fail
            - --silent
            - --show-error
            - --max-time
            - "9"
            - http://localhost:8000/v2/health/live
        initialDelaySeconds: 5
        periodSeconds: 30
        timeoutSeconds: 10
  builtInAdapter:
    serverType: triton
    runtimeManagementPort: 8001
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
  volumes:
    - name: dshm
      emptyDir:
        sizeLimit: 2048Mi
        medium: Memory

